name: Build project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [windows-2019]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: 5.x
    - name: Restore
      run: nuget.exe restore MathLib.sln
      shell: cmd
    - name: Build
      run: msbuild.exe MathLib.sln /t:Build /p:Configuration=Release
      shell: cmd
    - name: Tests
      run: msbuild.exe MathLib.sln /t:Test /p:Configuration=Release
      shell: cmd
